version: '3'
services:
  db:
    image: "mongo:latest"
    container_name: "reading-list-db-dev"
  server:
    image: "reading-list-dev-runner:master"
    ports:
      - "3001:3000"
    links:
      - db
    volumes:
      - ../../../node_modules:/usr/app/node_modules
      - ../../../dist/app/server:/usr/app
    container_name: "reading-list-server-dev"
    command: [nodemon, index.js]

  client:
    image: "reading-list-dev-runner:master"
    ports:
      - "3000:3000"
    links:
      - server
    volumes:
      - ../../../node_modules:/usr/app/node_modules
      - ../../../dist/app/client:/usr/app
    container_name: "reading-list-client-dev"
    command: [nodemon, index.js]
